// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GameConfig
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct BattleUnit : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static BattleUnit GetRootAsBattleUnit(ByteBuffer _bb) { return GetRootAsBattleUnit(_bb, new BattleUnit()); }
  public static BattleUnit GetRootAsBattleUnit(ByteBuffer _bb, BattleUnit obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public BattleUnit __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(6); }
  public string Description { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDescriptionBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetDescriptionBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetDescriptionArray() { return __p.__vector_as_array<byte>(8); }
  public GameConfig.CustomType Description2 { get { int o = __p.__offset(10); return o != 0 ? (GameConfig.CustomType)__p.bb.GetInt(o + __p.bb_pos) : GameConfig.CustomType.None; } }

  public static Offset<GameConfig.BattleUnit> CreateBattleUnit(FlatBufferBuilder builder,
      uint id = 0,
      StringOffset nameOffset = default(StringOffset),
      StringOffset descriptionOffset = default(StringOffset),
      GameConfig.CustomType description2 = GameConfig.CustomType.None) {
    builder.StartTable(4);
    BattleUnit.AddDescription2(builder, description2);
    BattleUnit.AddDescription(builder, descriptionOffset);
    BattleUnit.AddName(builder, nameOffset);
    BattleUnit.AddId(builder, id);
    return BattleUnit.EndBattleUnit(builder);
  }

  public static void StartBattleUnit(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddId(FlatBufferBuilder builder, uint id) { builder.AddUint(0, id, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(1, nameOffset.Value, 0); }
  public static void AddDescription(FlatBufferBuilder builder, StringOffset descriptionOffset) { builder.AddOffset(2, descriptionOffset.Value, 0); }
  public static void AddDescription2(FlatBufferBuilder builder, GameConfig.CustomType description2) { builder.AddInt(3, (int)description2, 0); }
  public static Offset<GameConfig.BattleUnit> EndBattleUnit(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<GameConfig.BattleUnit>(o);
  }
}


static public class BattleUnitVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 4 /*uint*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*Name*/, false)
      && verifier.VerifyString(tablePos, 8 /*Description*/, false)
      && verifier.VerifyField(tablePos, 10 /*Description2*/, 4 /*GameConfig.CustomType*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
